config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/about', to: 'static_pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
  
  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb:'150x150#'}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title,:body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end  

  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <% if user_signed_in? %>
    <%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure ?'} %>
  <% end %>
    <div class="border">
    </div>

</div>
<br/>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :Name %><br />
    <%= f.text_field :name, :placeholder => "What is your name ?" %>
  </p>

  <p>
    <i class="material-icons prefix">mode_edit</i>
    <%= f.label :Comment %><br />
    <%= f.text_area :body, :placeholder => "Add comment here...", :class => 'materialize-textarea' %>
  </p>
  <br/>

  <button class="submit btn waves-effect waves-light" type="submit" name="action">Submit
  <i class="material-icons right">done</i>
  </button>

<% end %>  
<br/>
<br/>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'> 
</head>
<body>
  <div id= 'sidebar'>
    <div id= 'logo'>
      <img src= ''/>
    </div>
    
    <ul id="slide-out" class="side-nav fixed">
      <p class= 'category'>Website</p>
      <div class= 'side_links'>
        <p><%= link_to 'Blog', root_path %></p>
        <p><%= link_to 'About', about_path %></p>
      </div>

    <ul>
      <p class= 'category'>Social</p>
        <div class= 'side_links'>
          <p><a href='https://www.instagram.com/scot_chard/' target='blank'>Instagram</a></p>
          <p><a href='https://github.com/Scotchard22' target='blank'>Github</a></p>
          <p><a href='https://www.linkedin.com/in/scotchard' target='blank'>LinkedIn</a></p>
          <p><a href='mailto:scot.c.chard@gmail.com'>Email</a></p>
        </div>  
    </ul>
    <% if !user_signed_in? %>
      <div class= 'side_links'>
        <p class=><%= link_to 'Admin Login', new_user_session_path %></p>
      </div>
    <% end %>  
  </div>
    </ul>

  <div id="main_content">
    <div class="header">
      <header id= 'all_posts'><%= link_to 'All Posts', root_path %> </header>
        <% if user_signed_in? %>
          <div class="buttons">
            <button class= 'button'><%= link_to 'Log Out', destroy_user_session_path %></button>
            <button class= 'button'><%= link_to 'New Post', new_post_path %></button>
          </div>
        <% end %>  
       <div id="header_border">
       </div> 
    </div>
    <div class="about_wrapper">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: 'alert') %>
      <% end %>  
    </div>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <p>
    <%= f.label :"Title of Post" %><br />
    <%= f.text_field :title, :placeholder => "What's the Title ?" %>
  </p>  

  <p>
  <i class="material-icons prefix">mode_edit</i>
    <%= f.label :Message %><br />
    <%= f.text_area :body, :placeholder => "Write Something...", :class => 'materialize-textarea' %> 
  </p> 

  <p>
    <%= f.label :"Upload an Image" %><br />
    <%= f.file_field :image, :placeholder => "Upload an Image" %>
  </p>  

  <button class="submit btn waves-effect waves-light" type="submit" name="action">Submit
  <i class="material-icons right">done</i>
  </button>

  <% end %>

app/views/posts/edit.html.erb
<div class="view_wrapper">
  <h4 class= 'post_header'> Edit Post </h4>
  <br/>
    
  <%= render 'form' %>

</div>  

app/views/posts/index.html.erb
</br>
<div class="page_wrapper">
  <% @posts.each do |post| %>
    <div class= 'post_wrapper'>
      <h2 class= 'title'><%= link_to post.title, post %></h2>

      <p class= 'date'><%= post.created_at.strftime('%B, %d, %Y') %></p>  
      <br/>
    </div>
    <br/>
    <br/>
  <% end %>    
</div>

app/views/posts/new.html.erb
<div class="view_wrapper">

  <%= form_for :post, url: posts_path do |f| %>

    <label for="first_name">Title of Post</label>
    <input placeholder= "What's the Title ?" id="first_name" type="text" class="validate">

    <i class="material-icons prefix">mode_edit</i>
    <label for="icon_prefix2">Message</label>
    <textarea placeholder= 'Write Something...' id="icon_prefix2" class="materialize-textarea"></textarea>

    <button class="submit btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">done</i>
    </button>

  <% end %>  
</div>  

app/views/posts/show.html.erb
<div class="view_wrapper">
  <h1 class= 'title'>
    <%= @post.title %>
  </h1>  

  <%= image_tag @post.image.url(:large) %>
  <br>
  <br>
  <p class='post_body'>
    <%= @post.body %>
  </p>  
  <br>
  <br>
  <p class= 'date'>
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure ?"} %>
    <% end %>
  </p>
  <br/>
  <br/>
  <br/>
  <div id="comments">
    <h5 class='comment_header'><%= @post.comments.count %> Comments:</h5>
    <br/>
    <%= render @post.comments %>
    <br/>
    <br/>
    <h5 class='comment_header'>Add a comment:</h5>
    <%= render "comments/form" %>
  </div>

</div>    

app/views/static_pages/about.html.erb
<div class="about_wrapper"> 
  <img class="profile center-align responsive-image" src="pic51.jpg" style="width:300px;height:300px; border-radius:30px;"/>

  <div class="side_text">
    <span class='name'>Scot Chard</span> 
    <h5 class="recent"> I am a Junior Full-Stack Developer.</h5>
    <h5 class="recent"> I am currently looking for work.</h5>
    <div class='about_links'>
      <h5 class="recent">Recent projects I've worked on:</h5>
      <p><a href='https://github.com/Scotchard22/My_Blog' target='blank'>This blog</a></p>
      <p><a href='https://github.com/Scotchard22/Linkage' target='blank'>Linkage</a></p>
      <p><a href='https://github.com/Scotchard22/SVJ_Photography' target='blank'>SVJ Photography</a></p>
      <p><a href='https://github.com/Scotchard22/SVJ_Photography' target='blank'>What's On Your Agenda?</a></p>
    </div>  
  </div>
  <br/>
  <br/>
  <div class='about_text'>

    He has a huge passion for traveling which has sparked a big interest in photography. Photography is one of the greatest forms of art. It isn't just a simply capturing images of a place, a thing, or a person. Photography is capturing the most valuable moments in your life, and making them timeless. It captures the moment along with feelings and memories that go along with the image at that current time. This is why he loves photography. 
  </div>
</div>